# Generated by Django 4.2.7 on 2023-12-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_rename_unit_number_unit_unit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='unit_id',
            field=models.IntegerField(default=1),
        ),
    ]
