# Generated by Django 4.2.7 on 2023-12-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_problem_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='problem',
            field=models.ManyToManyField(limit_choices_to={'unit_id__icontains': models.IntegerField()}, to='tutor.problem'),
        ),
    ]
