# Generated by Django 4.2.7 on 2023-12-17 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_alter_unit_problem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='problem',
            new_name='problems',
        ),
    ]
