# Generated by Django 4.2.7 on 2023-12-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_rename_problem_unit_problems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='expression',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
