# Generated by Django 4.2.7 on 2023-12-17 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_remove_grade_unit_grade_grade_id_grade_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='unit_id',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='grade_id',
        ),
        migrations.AddField(
            model_name='problem',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_problems', to='tutor.unit'),
        ),
        migrations.AddField(
            model_name='unit',
            name='grade',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='related_units', to='tutor.grade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='units',
            field=models.ManyToManyField(related_name='related_grades', to='tutor.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='problems',
            field=models.ManyToManyField(related_name='related_units', to='tutor.problem'),
        ),
    ]
