# Generated by Django 4.2.7 on 2023-12-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_remove_problem_expression'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expression',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
