# Generated by Django 4.2.7 on 2023-12-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_problem_expression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='units',
            field=models.ManyToManyField(limit_choices_to={'grade__icontains': models.IntegerField(default=3)}, related_name='related_grades', to='tutor.unit'),
        ),
    ]
