# Generated by Django 4.2.7 on 2023-12-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0012_alter_grade_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='grade',
            name='units',
            field=models.ManyToManyField(related_name='related_grades', to='tutor.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='related_units', to='tutor.grade'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(default=1),
        ),
    ]
