# Generated by Django 4.2.7 on 2023-12-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_grade_problem_unit_delete_postitem_grade_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='problem',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
